import {
    Users,
    Briefcase,
    FileText,
    DollarSign,
    Wrench,
    BarChart3,
    Settings,
    Shield,
    Search,
    Plus,
    Bell,
    MapPin,
    CheckCircle2,
    AlertCircle,
    Check,
    X,
    ChevronRight,
    Star,
    Printer,
    Menu,
    LogOut,
    Eye,
    Calendar,
    Filter,
    Calculator,
    History,
    Trash2,
    Phone,
    MessageSquare,
    Play,
    Settings2,
    Box,
    PlayCircle,
    Warehouse,
    RotateCcw,
    ShieldCheck,
    Truck,
    LayoutDashboard,
    Factory
} from "lucide-react";

export const Icons = {
    // Lotus icons
    logo: Printer,
    users: Users,
    sales: Briefcase,
    leads: Users,
    quotes: FileText,
    accounting: DollarSign,
    service: Wrench,
    reports: BarChart3,
    settings: Settings,
    admin: Shield,
    search: Search,
    add: Plus,
    bell: Bell,
    location: MapPin,
    check: CheckCircle2,
    warning: AlertCircle,
    menu: Menu,
    logout: LogOut,
    arrowRight: ChevronRight,
    calendar: Calendar,
    filter: Filter,
    calculator: Calculator,
    history: History,
    delete: Trash2,
    view: Eye,
    printer: Printer,
    phone: Phone,
    message: MessageSquare,
    play: Play,

    // Indus original icons mapped or preserved
    dashboard: LayoutDashboard,
    crm: Users,
    mold: Settings2,
    costing: Calculator,
    inventory: Warehouse,
    production: PlayCircle,
    rts: RotateCcw,
    qc: ShieldCheck,
    scrap: Trash2,
    dispatch: Truck,
    finance: FileText,
    factory: Factory,
    close: X,
};
